/** @type {import("snowpack").SnowpackUserConfig} */
module.exports = {
  mount: {
    public: { url: "/", static: true },
    src: { url: "/dist" },
  },
  plugins: ["@snowpack/plugin-dotenv", "@snowpack/plugin-typescript"],
  packageOptions: {
    knownEntrypoints: [
      "@reach/utils/can-use-dom",
      "@reach/utils/clone-valid-element",
      "@reach/utils/compose-event-handlers",
      "@reach/utils/compose-refs",
      "@reach/utils/computed-styles",
      "@reach/utils/context",
      "@reach/utils/dev-utils",
      "@reach/utils/get-document-dimensions",
      "@reach/utils/get-scroll-position",
      "@reach/utils/get-scrollbar-offset",
      "@reach/utils/is-right-click",
      "@reach/utils/make-id",
      "@reach/utils/noop",
      "@reach/utils/owner-document",
      "@reach/utils/polymorphic",
      "@reach/utils/type-check",
      "@reach/utils/types",
      "@reach/utils/use-constant",
      "@reach/utils/use-controlled-state",
      "@reach/utils/use-event-listener",
      "@reach/utils/use-focus-change",
      "@reach/utils/use-force-update",
      "@reach/utils/use-isomorphic-layout-effect",
      "@reach/utils/use-lazy-ref",
      "@reach/utils/use-previous",
      "@reach/utils/use-stable-callback",
      "@reach/utils/use-stateful-ref-value",
      "@reach/utils/use-update-effect",
    ],
  },
};
